project:
  type: website
  output-dir: docs

website:
  title: "AnTIDOTe Trial"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: protocol.qmd
        text: Protocol
      - href: sap.qmd
        text: Statistical analysis plan
      - href: dmp.qmd
        text: Data management plan
      - href: data.qmd
        text: Trial data
      - href: team.qmd
        text: Team
      - href: anakinra.qmd
        text: Anakinra
      - href: hip.qmd
        text: Hip fracture
      - href: funding.qmd
        text: Funding
      - about.qmd
format:
  html:
    theme: darkly
    css: styles.css

editor: source

