project:
  type: website
  output-dir: docs

website:
  title: "AnTIDOTe Trial"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: sap.qmd
        text: Statistical analysis plan
      - href: protocol.qmd
        text: Protocol
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css

editor: source

