---
title: "About"
---

## About this site

This website has been constructed using R, RStudio, Git, Github and Github Pages. Together, these technologies allow collaborative working on projects in which every step needs to be version-controlled. Version control is increadibly important in complex modern science projects, in order that the public can have confidence in government, charity and philanthropic monies well spent, scientific colleagues can have confidence in the replicability of results, and team members are able to work in flexible ways on a complex, multifaceted project. 

## What is Quarto?

"Quarto" is a software for "marking up" documents using "Markdown", a simple labelling language which allows text editors to turn programmable text into the kind of text you see in Word or PDF documents - Rich Text, or HTML for webpages. Why is is this useful? Quarto means that documents can be created and re-created on-the-fly, reproducibly and in such a fashion that every line-change can be audited.

[Learn more here](https://quarto.org/)

## What is R?

R is a programming language and programming environment for statisitcs, simulation, and reproducible research. Reproducible research means that every step in every analysis is transparent, and that the researchers' intentions are clear, set out beforehand and often, that analyses are pre-registered in order to prevent hypothesising after the results are known. R helps researchers to do reproducible research by making sure every step of every analysis is stored.

[Learn more here](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)

## What is Git?

Git is software for version control. The three core actions involved in using Git are Commit (commit changes) push(push to a repository) and pull(get from a repository). Git is the core of many software development projects, from small scale science projects to multinational companies who keep the internet 'on' and planes flying.

[Learn more here](https://en.wikipedia.org/wiki/Git)

## What is Github?

Github is an online repository which stores version-controlled software. It is be far the most popular warehouse of such repositories or (repos).  The repo can be archived and re-used for other projects. It can be downloaded and the code re-run by interested parties. All the contents are licensed under an [MIT Open Source license](https://opensource.org/licenses/MIT). 

[Learn more here](https://lab.github.com/githubtraining/introduction-to-github)

<div class="hide" color="lightgrey">
Copyright 2022, Dr. Ross A. Dunne

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
</div>

